#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "########## Update system"
read -p "Are you sure? [y/n]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  sudo pacman -Syu --noconfirm
fi

echo "########## Installing packages with pacman"
read -p "Are you sure? [y/n]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  sudo pacman -S --noconfirm --needed wget git firefox thunderbird \
    alacritty highlight ranger neovim lazygit sway swaybg mpv grim swaylock \
    swayidle go npm telegram-desktop pamixer xdg-desktop-portal-wlr \
    xdg-desktop-portal-gtk flameshot jq btop brightnessctl foot wl-clipboard \
    wtype profile-sync-daemon
fi

echo "########## Installing packages from AUR with yay"
read -p "Are you sure? [y/n]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  yay -S --noconfirm --needed code-marketplace rofi-lbonn-wayland \
    visual-studio-code-bin
fi

echo "########## Setting dark theme system wide"
read -p "Are you sure? [y/n]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
  gsettings set org.gnome.desktop.interface color-scheme prefer-dark
fi

echo "########## Overwrite gdm rules for allowing Wayland"
read -p "Are you sure? [y/n]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  sudo ln -s /dev/null /etc/udev/rules.d/61-gdm.rules
fi

echo "########## Enable tap-to-click in gdm"
read -p "Are you sure? [y/n]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  sudo mkdir -p /etc/dconf/db/gdm.d
  sudo ln -s ~/other-dots/06-tap-to-click /etc/dconf/db/gdm.d/
fi

echo "########## Use nvidia with sway + specific env variables"
read -p "Are you sure? [y/n]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  sudo ln ~/other-dots/sway-nvidia.* /usr/share/wayland-sessions/
fi

echo "########## Increment parallel download count"
read -p "Are you sure? [y/n]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  sudo sed -i "s/ParallelDownloads = [[:digit:]]\+/ParallelDownloads = 10/1" /etc/pacman.conf
fi

echo "########## Generating SSH keys with ed25519 algorithm"
read -p "Are you sure? [y/n]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "Which mail are you using?"
  read -p 'Mail: ' mail
  ssh-keygen -t ed25519 -C $mail
fi

echo "########## Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:konova8/dots.git"

echo "########## Activate Daemon for firefox profile on RAM"
read -p "Are you sure? [y/n]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  sudo systemctl --user enable psd.service
fi

echo -e "########## Remeber to do these other things:\n \
- Change this setting in about:config in firefox\n \
  - toolkit.tabbox.switchByScrolling = true\n \
  - browser.cache.disk.parent_directory = /run/user/1000/firefox\n \
- Add SSH key to GitHub\n \
- Import settings for YT browser extension\n \
- Check if ibus is working (split keyboard)\n \
- Configure Thunderbird"
